### ISSUE TITLE
invalid rig model

### ISSUE THREAD

**Issue by ea3hsp** [dh1tw/gorigctl#3]
I don't know why I always getting invalid rig model, my model is ft450d (127) on rigctld and rigctl is working fine. Any idea?

PS: gorigctl server mqtt -m 127 -p 10085 -u "10.1.2.10" -o "/dev/ttyUSB0" -X "ea3hsp"

**Comment by dh1tw** [comment]
strange... the syntax how you call gorigctl looks fine. Does it work properly with the default model (1 - dummy rig)  ?

**Comment by ea3hsp** [comment]
I got the same issue using dummy rig. But in the other hand if I use: gorigctl cli local -m 127 -o "/dev/ttyUSB0" -b 38400 works fine ...

PS: 08:11:58 Connected to MQTT Broker 10.1.2.10:10085
connstatus: 1
08:11:59 init_rig: invalid rig model

**Comment by dh1tw** [comment]
fixed in [gorigctl 0.1.1](https://github.com/dh1tw/gorigctl/releases). It appears that I had this already fixed manually on the remote server but not committed into the repo. I basically just forgot the pass the pflag values into the function.
If it works also on your side, please feel free to close the issue.
